"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../../../../lib/supabase/client";

type Course = { id: string; title: string; status: string; credential_type: string; duration: string | null; fee: number | null; created_at: string };
type Enquiry = { id: string; message: string | null; status: string; created_at: string; course: { title: string } | null };

export default function InstituteDashboard() {
  const supabase = createClient(); const [courses,setCourses]=useState<Course[]>([]); const [enquiries,setEnquiries]=useState<Enquiry[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setError("Please log in first.");setLoading(false);return;} const {data:inst}=await supabase.from("institutes").select("id,name").eq("owner_id",user.id).maybeSingle(); if(!inst){setError("No institute profile found. Start by registering your institute.");setLoading(false);return;} const {data:c}=await supabase.from("courses").select("id,title,status,credential_type,duration,fee,created_at").eq("institute_id",inst.id).order("created_at",{ascending:false}); const {data:e}=await supabase.from("course_enquiries").select("id,message,status,created_at,course:courses(title)").order("created_at",{ascending:false}); setCourses(c||[]); setEnquiries((e||[]) as unknown as Enquiry[]);setLoading(false);})()},[]);
  const statusClass=(s:string)=>s==="approved"?"bg-emerald-50 text-emerald-700":s==="rejected"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700";
  return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/courses" className="text-2xl font-black">Hospire</Link><Link href="/courses/institute" className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white">+ Add program</Link></div></header><section className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-black uppercase tracking-widest text-blue-700">Institute dashboard</p><h1 className="mt-2 text-4xl font-black">Manage your programs & enquiries.</h1>{loading?<p className="mt-8 text-slate-500">Loading...</p>:error?<div className="mt-8 rounded-2xl bg-white p-7 ring-1 ring-slate-200"><p className="font-bold text-slate-700">{error}</p><Link href="/courses/institute" className="mt-4 inline-block font-black text-blue-700">Create institute profile →</Link></div>:<><div className="mt-8 grid gap-5 sm:grid-cols-3"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Programs</p><b className="mt-2 block text-3xl">{courses.length}</b></div><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Approved</p><b className="mt-2 block text-3xl">{courses.filter(x=>x.status==="approved").length}</b></div><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Enquiries</p><b className="mt-2 block text-3xl">{enquiries.length}</b></div></div><section className="mt-8 rounded-3xl bg-white p-7 ring-1 ring-slate-200"><h2 className="text-2xl font-black">Your programs</h2><div className="mt-5 divide-y divide-slate-100">{courses.map(c=><div key={c.id} className="flex flex-col gap-3 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black">{c.title}</h3><p className="mt-1 text-sm text-slate-500">{c.credential_type} • {c.duration||"Flexible"} {c.fee!=null?`• INR ${Number(c.fee).toLocaleString("en-IN")}`:""}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-black ${statusClass(c.status)}`}>{c.status}</span></div>)}{!courses.length&&<p className="py-6 text-slate-500">No programs yet.</p>}</div></section><section className="mt-8 rounded-3xl bg-white p-7 ring-1 ring-slate-200"><h2 className="text-2xl font-black">Recent enquiries</h2><div className="mt-5 divide-y divide-slate-100">{enquiries.slice(0,20).map(e=><div key={e.id} className="py-5"><div className="flex justify-between gap-3"><b>{e.course?.title||"Program"}</b><span className="text-xs font-bold text-slate-400">{new Date(e.created_at).toLocaleDateString("en-IN")}</span></div><p className="mt-2 text-sm text-slate-600">{e.message||"Interested in this program."}</p></div>)}{!enquiries.length&&<p className="py-6 text-slate-500">No enquiries yet.</p>}</div></section></>}</section></main>;
}
