"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../../../lib/supabase/client";

type Institute={id:string;name:string;city:string|null;status:string;is_verified:boolean}; type Course={id:string;title:string;status:string;credential_type:string;duration:string|null;fee:number|null;institute_id:string;institute:Institute|null};
export default function CoursesAdmin(){const supabase=createClient();const[courses,setCourses]=useState<Course[]>([]);const[loading,setLoading]=useState(true);const[denied,setDenied]=useState(false);const[busy,setBusy]=useState("");
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setDenied(true);setLoading(false);return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin"){setDenied(true);setLoading(false);return;}await load();setLoading(false)})()},[]);
const load=async()=>{const{data}=await supabase.from("courses").select("id,title,status,credential_type,duration,fee,institute_id,institute:institutes(id,name,city,status,is_verified)").order("created_at",{ascending:false});setCourses((data||[]) as unknown as Course[])};
const approve=async(c:Course,ok:boolean)=>{setBusy(c.id);const{error}=await supabase.from("courses").update({status:ok?"approved":"rejected"}).eq("id",c.id);if(!error){if(ok&&c.institute_id)await supabase.from("institutes").update({status:"approved",is_verified:true}).eq("id",c.institute_id);await load()}setBusy("")};
if(loading)return <main className="min-h-screen grid place-items-center font-bold text-slate-500">Loading admin...</main>;if(denied)return <main className="min-h-screen grid place-items-center px-5 text-center"><div><div className="text-5xl">🔒</div><h1 className="mt-4 text-2xl font-black">Admin access required</h1><Link href="/courses" className="mt-5 inline-block font-black text-blue-700">← Courses</Link></div></main>;
return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/courses" className="text-2xl font-black">Hospire</Link><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">Course moderation</span></div></header><section className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-4xl font-black">Review courses & institutes.</h1><p className="mt-2 text-slate-500">Approve genuine programs before they appear publicly.</p><div className="mt-8 space-y-4">{courses.map(c=><article key={c.id} className="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${c.status==="approved"?"bg-emerald-50 text-emerald-700":c.status==="rejected"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{c.status}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{c.credential_type}</span></div><h2 className="mt-3 text-xl font-black">{c.title}</h2><p className="mt-1 text-sm font-bold text-slate-600">{c.institute?.name||"Unknown institute"}{c.institute?.city?` • ${c.institute.city}`:""}</p><p className="mt-2 text-sm text-slate-500">{c.duration||"Flexible"}{c.fee!=null?` • INR ${Number(c.fee).toLocaleString("en-IN")}`:""}</p></div><div className="flex gap-2">{c.status!=="approved"&&<button disabled={busy===c.id} onClick={()=>approve(c,true)} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">Approve</button>}{c.status!=="rejected"&&<button disabled={busy===c.id} onClick={()=>approve(c,false)} className="rounded-xl bg-red-50 px-5 py-3 text-sm font-black text-red-700 disabled:opacity-50">Reject</button>}</div></div></article>)}{!courses.length&&<div className="rounded-3xl bg-white p-12 text-center text-slate-500 ring-1 ring-slate-200">No course submissions yet.</div>}</div></section></main>}
