"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

const categories = ["Luxury Hotels","Restaurants & Cafés","Cloud Kitchens","Airlines & Cruises","Street Food & Independent Food Businesses","Catering & Events","Resorts","Corporate / Institutional Hospitality"];

export default function PostJobPage() {
 const router=useRouter(); const supabase=createClient();
 const [checking,setChecking]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [companyName,setCompanyName]=useState(""); const [category,setCategory]=useState(""); const [companyCity,setCompanyCity]=useState("");
 const [title,setTitle]=useState(""); const [department,setDepartment]=useState(""); const [location,setLocation]=useState(""); const [jobType,setJobType]=useState("full-time");
 const [expMin,setExpMin]=useState(""); const [expMax,setExpMax]=useState(""); const [salaryMin,setSalaryMin]=useState(""); const [salaryMax,setSalaryMax]=useState("");
 const [description,setDescription]=useState(""); const [requirements,setRequirements]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/");return;} const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle(); if(p?.role!=="employer"){setError("You need an employer account to post a job. Choose “Hiring talent” when creating your account.");setChecking(false);return;} const {data:c}=await supabase.from("companies").select("name,company_type,city").eq("owner_id",user.id).maybeSingle(); if(c){setCompanyName(c.name||"");setCategory(c.company_type||"");setCompanyCity(c.city||"");} setChecking(false);})();},[router,supabase]);
 async function submit(e:FormEvent){e.preventDefault();setError(""); if(!companyName.trim()||!category||!title.trim()||!location.trim()){setError("Please complete company name, hiring category, job title and location.");return;} const a=expMin?Number(expMin):null,b=expMax?Number(expMax):null,c=salaryMin?Number(salaryMin):null,d=salaryMax?Number(salaryMax):null; if([a,b,c,d].some(n=>n!==null&&(!Number.isFinite(n)||n<0))){setError("Experience and salary must be valid numbers.");return;} if(a!==null&&b!==null&&b<a){setError("Maximum experience cannot be lower than minimum.");return;} if(c!==null&&d!==null&&d<c){setError("Maximum salary cannot be lower than minimum.");return;} setSaving(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/");return;} const {data:company,error:ce}=await supabase.from("companies").upsert({owner_id:user.id,name:companyName.trim(),company_type:category,city:companyCity.trim()||null},{onConflict:"owner_id"}).select("id").single(); if(ce||!company){setError(ce?.message||"Could not save employer profile.");setSaving(false);return;} const {error:je}=await supabase.from("jobs").insert({company_id:company.id,title:title.trim(),department:department.trim()||null,location:location.trim(),experience_min:a,experience_max:b,salary_min:c,salary_max:d,job_type:jobType,description:description.trim()||null,requirements:requirements.trim()||null,is_active:true}); if(je){setError(je.message);setSaving(false);return;} router.push("/opportunities");router.refresh(); }
 if(checking)return <main className="min-h-screen bg-slate-100 flex items-center justify-center"><div className="rounded-3xl bg-white p-10 font-bold text-slate-500">Checking employer access...</div></main>;
 return <main className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><Link href="/" className="text-2xl font-black">Hospire</Link><Link href="/opportunities" className="text-sm font-bold text-blue-700">← Opportunities</Link></div></header>
 <section className="mx-auto max-w-4xl px-5 py-10 sm:py-14"><p className="text-sm font-black uppercase tracking-widest text-blue-700">Employer hiring</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Post an opportunity.</h1><p className="mt-3 max-w-2xl text-slate-500">Tell hospitality professionals exactly who you need — from a luxury hotel chef to a trained street-food kitchen worker.</p>
 {error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm font-bold text-red-700">{error}</div>}
 <form onSubmit={submit} className="mt-8 space-y-6">
 <section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-black">1. Business</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Business / employer name *" value={companyName} set={setCompanyName} placeholder="e.g. Sharma Momos"/><label><span className="mb-2 block text-sm font-bold">Hiring category *</span><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-4"><option value="">Select category</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Business city" value={companyCity} set={setCompanyCity} placeholder="Delhi"/></div></section>
 <section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-black">2. Job details</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Job title *" value={title} set={setTitle} placeholder="Commis Chef, Barista, F&B Steward..."/><Field label="Department" value={department} set={setDepartment} placeholder="Kitchen / Front Office / F&B"/><Field label="Job location *" value={location} set={setLocation} placeholder="Mumbai, Maharashtra"/><label><span className="mb-2 block text-sm font-bold">Job type</span><select value={jobType} onChange={e=>setJobType(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-4"><option>full-time</option><option>part-time</option><option>contract</option><option>internship</option></select></label></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Minimum experience (years)" value={expMin} set={setExpMin} placeholder="0"/><Field label="Maximum experience (years)" value={expMax} set={setExpMax} placeholder="3"/><Field label="Minimum salary / month" value={salaryMin} set={setSalaryMin} placeholder="18000"/><Field label="Maximum salary / month" value={salaryMax} set={setSalaryMax} placeholder="25000"/></div></section>
 <section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-black">3. Role & requirements</h2><label className="mt-5 block"><span className="mb-2 block text-sm font-bold">Job description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={6} placeholder="Describe the day-to-day work, team and workplace..." className="w-full resize-none rounded-xl border border-slate-200 p-4"/></label><label className="mt-5 block"><span className="mb-2 block text-sm font-bold">Skills / requirements</span><textarea value={requirements} onChange={e=>setRequirements(e.target.value)} rows={6} placeholder="Example: hygiene, knife skills, recipe consistency, tandoor, 1+ year experience..." className="w-full resize-none rounded-xl border border-slate-200 p-4"/></label></section>
 <button type="submit" disabled={saving} className="w-full rounded-2xl bg-blue-700 px-6 py-5 text-lg font-black text-white shadow-lg hover:bg-blue-800 disabled:opacity-60">{saving?"Publishing opportunity...":"Publish opportunity →"}</button></form></section></main>
}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 p-4 outline-none focus:border-blue-600"/></label>}